package br.com.db1.start.tipo;

public enum TipoLogradouro {

	VILA, LARGO, TRAVESSA, VIELA, LOTEAMENTO, PATIO, VIADUTO, AREA, VIA, AEROPORTO, VEREDA, DISTRITO, VALE, NUCLEO, TREVO, FAZENDA, TRECHO, ESTRADA, SITIO, FEIRA, SETOR, MORRO, RUA, CHACARA, RODOVIA, RESIDENCIAL, AVENIDA, COLONIA, RECANTO, QUADRA, PRACA, CONDOMINIO, PASSARELA, PARQUE, ESPLANADA, LAGOA, FAVELA, LADEIRA, LAGO, CONJUNTO, JARDIM, ESTACAO, CAMPO, ALAMEDA,;
}
